kind: Service
apiVersion: v1
metadata:
  name: doneill-echo-service
  namespace: doneill
  labels:
    tier: seneca-services
    domain: seneca-base
spec:
  selector:
    srv: echo-service
  ports:
  - name: mesh
    port: 39999
  - name: repl
    port: 10001
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: doneill-echo-service
  namespace: doneill
spec:
  replicas: 1
  selector:
    matchLabels:
      srv: echo-service
  template:
    metadata:
      labels:
        srv: echo-service
        domain: seneca-base
    spec:
      containers:
      - name: echo-service
        image: doneill/echo-service
        imagePullPolicy: IfNotPresent
        ports:
        - name: mesh
          containerPort: 39999
        - name: repl
          containerPort: 10001